# Generated by Django 2.0.3 on 2018-03-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'algorithms',
            },
        ),
        migrations.CreateModel(
            name='PackingObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_width', models.IntegerField()),
                ('_height', models.IntegerField()),
                ('x_coordinate', models.IntegerField(null=True)),
                ('y_coordinate', models.IntegerField(null=True)),
                ('background_color', models.CharField(max_length=10, null=True)),
                ('rotated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'packing_objects',
            },
        ),
        migrations.CreateModel(
            name='PackingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'packing_spaces',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_tooltips', models.BooleanField(default=True)),
                ('selected_algorithm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Algorithm')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session')),
            ],
            options={
                'db_table': 'session_configurations',
            },
        ),
        migrations.AddField(
            model_name='packingspace',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
        migrations.AddField(
            model_name='packingobject',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Session'),
        ),
    ]
