// Packing objects
export const CLEAR_PACKED_OBJECTS = 'CLEAR_PACKED_OBJECTS';
export const CREATE_PACKING_OBJECTS = 'CREATE_PACKING_OBJECTS';
export const DELETE_PACKING_OBJECTS = 'DELETE_PACKING_OBJECTS';
export const START_UPDATE_PACKING_OBJECT = 'START_UPDATE_PACKING_OBJECT';
export const UPDATE_PACKING_OBJECT = 'UPDATE_PACKING_OBJECT';

// Packing space
export const START_UPDATE_PACKING_SPACE = 'START_UPDATE_PACKING_SPACE';
export const UPDATE_PACKING_SPACE = 'UPDATE_PACKING_SPACE';

// Solves
export const SOLVER_SUCCESS = 'SOLVER_SUCCESS';

// Sessions
export const GET_SESSIONS = 'GET_SESSIONS';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const CREATE_SESSION = 'CREATE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';

// Settings
export const GET_SETTINGS = 'GET_SETTINGS';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

// App data loading
export const START_LOAD = 'START_LOAD';
export const END_LOAD = 'END_LOAD';
