// Packing objects
export const CLEAR_PACKED_OBJECTS = 'CLEAR_PACKED_OBJECTS';
export const CREATE_PACKING_OBJECTS = 'CREATE_PACKING_OBJECTS';
export const DELETE_PACKING_OBJECTS = 'DELETE_PACKING_OBJECTS';
export const GET_PACKING_OBJECTS = 'GET_PACKING_OBJECTS';
export const UPDATE_PACKING_OBJECT = 'UPDATE_PACKING_OBJECT';

// Packing space
export const GET_PACKING_SPACE = 'GET_PACKING_SPACE';
export const UPDATE_PACKING_SPACE = 'UPDATE_PACKING_SPACE';

// Solves
export const SOLVER_SUCCESS = 'SOLVER_SUCCESS';

// Sessions
export const GET_SESSIONS = 'GET_SESSIONS';
export const UPDATE_SESSION = 'UPDATE_SESSION';
export const CREATE_SESSION = 'CREATE_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';
